@echo off
mkdir screens

echo Downloading 1. Imposter - Voting (Offline)
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzMyYzdjMmNkMjY5ZTQzZmFiMWVmNWE5OGRkMDI5OTdiEgsSBxC8iqLb7QsYAZIBIwoKcHJvamVjdF9pZBIVQhM3MjkwNjcwMTQxODE4OTU1ODQ2&filename=&opi=89354086" -o "screens/imposter_voting_offline.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujtbh5BLd-dOZxCuyIU0CTeXrNLW3QDcrU26NJ4Oaa205aVdGb6ivsLJ1J_WsWRHTJgvDhUqKkHj2XArzWeedTp13zCEQx-FNkyJD_nAaJzqhmv_HqGKq8tAzwegTybcnaVTZC-q0Tq5h0H2LFGp40Vh0Qkl1L7HVvHiqiGdXoWTSyGN3ek5v9TlbCsQYHf5_yB9WDIfsA1jpVF9P94rwAj4bYSGQ64XX8Q6O_IBLozp9AFj-ZFMYui5A" -o "screens/imposter_voting_offline.png"

echo Downloading 2. Imposter - Results
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzUxZDI1OTMyOTQ0ODRjNGE5ZGMwOWFmNWU1ZmQ0MjkwEgsSBxC8iqLb7QsYAZIBIwoKcHJvamVjdF9pZBIVQhM3MjkwNjcwMTQxODE4OTU1ODQ2&filename=&opi=89354086" -o "screens/imposter_results.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ugUT_HmnykyKee03z1xqnMM2bHN-ctb_fNjbsHmk5G5ToBsGB4_FH833WAIW5F0rNSLeyA4rRuGpNFmNS1aTgLx0qfya1MaRpMUocOCJEGXpX9xhRIK3NvgOGrhrrUnkMW9OCJL9RgI6mCLrQCBVvlMa6ARqAm4XQFkuVH_GbTaF7QF6zDJsxIEyk6oU8oQs-jMTF35fvQkMXWRZTjK9Z_U8TV6u8ElgNnOT9XFVgB0cP4pP9vzfmR_47s" -o "screens/imposter_results.png"

echo Downloading 3. Imposter - Online Entry
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzM0ZGY4MThmNDE3NDRmYjA5MWQ1NGE3MzEzMGM0MGI0EgsSBxC8iqLb7QsYAZIBIwoKcHJvamVjdF9pZBIVQhM3MjkwNjcwMTQxODE4OTU1ODQ2&filename=&opi=89354086" -o "screens/imposter_online_entry.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujA0yU0CEn4Fnm_MNk10UkQ-ht44wZ0ibHWjaxBlBI6fpU7byK-_ev0zY2gAY0x-BspBNSIxucWf3U_NePeybdrEkfktole6iAMItDPcxSEfDQekVIGrkM5prym5pdR3wWrgGdyzTEHuqBdfPRoSFTj_AqfoUGYwbbup1IqUAXVQ6fGhQ0lLFhC70L1Vremw1c2NAraApbbREXFykw8KHvcK_Q-dbh3qubXHC_1j1JF24xYKUFSog7ifQ" -o "screens/imposter_online_entry.png"

echo Downloading 4. Imposter - Online Reveal
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzUxZmM3ZmU4YjE1NzRjMjI4MDRkY2Q4ZjRiMmZmZmI5EgsSBxC8iqLb7QsYAZIBIwoKcHJvamVjdF9pZBIVQhM3MjkwNjcwMTQxODE4OTU1ODQ2&filename=&opi=89354086" -o "screens/imposter_online_reveal.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0ujCH9Or6QqkWpKvk-Fys10xlF9HiMhaqM-Q71ZmVPbQdvTNkG-hnXSdJuQJTWjmaWuX3CbB0cTz8oIraFXd_jNI-CFUbPicqM7sPBD7WC8Sw6ANWQzTe2I31kgRi7UPD7yLFaQJS-bdaP-iviZFfHa0M6_qTNfTc-UOIXHHIY4k32ddqk_GxaeDO-dbTxDMMzecOWZYJC38D2XGAhyzMxehhc1r9AxbUo1xlFpMR0PPVVSEQTAwgc1a3A" -o "screens/imposter_online_reveal.png"

echo Downloading 5. Imposter - Online Lobby
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2M4ZGU3OTAwZTQxNDQ2YTQ4YWMyMzEwMGIzNjNlZmQ4EgsSBxC8iqLb7QsYAZIBIwoKcHJvamVjdF9pZBIVQhM3MjkwNjcwMTQxODE4OTU1ODQ2&filename=&opi=89354086" -o "screens/imposter_online_lobby.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uh2jiDP7L2ryo_oXn6In6q7Fm1EopolhUlPDDHldshutV5RQs6BVnJd03EmJHXfyjt1pPYJQzKKJbUiDCPA3SYLOhAWYIcw6MdiXAr27dzwJmhQ8tVXQT9wHAPHRJhj6M2MYeWAceAv9WXZZFM8XiNxAa_ADD-vy58zvjJZ_ibpwLFgPKrDKWVwCNrIfGq3jsf55CREUlhJjqnIcupbW7EyKAZbnJJuV-_n3f_ZvlA7dVV-QmfwwSJ6Qbw" -o "screens/imposter_online_lobby.png"

echo Downloading 6. Imposter - Online Voting
curl -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2U2NmU5ZGIyNTA3MzRiNjM4Y2U2MTk3ZTUwOTViN2U1EgsSBxC8iqLb7QsYAZIBIwoKcHJvamVjdF9pZBIVQhM3MjkwNjcwMTQxODE4OTU1ODQ2&filename=&opi=89354086" -o "screens/imposter_online_voting.html"
curl -L "https://lh3.googleusercontent.com/aida/ADBb0uigLY0jQRNf_iGVMfeVNulZPEV4uTPzdbYOKY8yELFgKxFecZyEoQ6kbkp0NWmSUsLK3QlgrfB7oyMY6hDJVpqCmZ165fAiogyBRVA_Hir37X19vptbLt5tOsmrb2z4BvihO9FxNkAK3428-jXA3RTIiwIRBEEuBVmWJv37ZIi5C1u_Y6izCTfroK9y9-QU0f5tz_q0EanIlfum7aRms8Etij1XfXNqaKYnH6I3xY6YGUAzF282JJt1LIg" -o "screens/imposter_online_voting.png"

echo Done!
